# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm < Formula
  desc "SSH Session Manager - TUI tool for managing SSH connections"
  homepage "https://github.com/erhuoyan/ssm"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.3.1/ssm_0.3.1_darwin_amd64.tar.gz"
      sha256 "e5e86c26d05a8d18ba23b951cb50e70fdbbdfd1dbf69fda3a2ec4bcd3ec25c56"

      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.3.1/ssm_0.3.1_darwin_arm64.tar.gz"
      sha256 "71176600bcfe987599a1f083b69cdedb5237626c12f756abac3cc31fcc85b82b"

      define_method(:install) do
        bin.install "ssm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.3.1/ssm_0.3.1_linux_amd64.tar.gz"
      sha256 "a076237369f041ec61ec996af09c6d5843cba1cd836812bf7a6daf3bc0c95d51"
      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.3.1/ssm_0.3.1_linux_arm64.tar.gz"
      sha256 "61f2e4ddf615fd498208fe0b4b96d422cba5de1c3329b66251f036a05a6443a1"
      define_method(:install) do
        bin.install "ssm"
      end
    end
  end
end
