# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm < Formula
  desc "SSH Session Manager - TUI tool for managing SSH connections"
  homepage "https://github.com/erhuoyan/ssm"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.5.1/ssm_0.5.1_darwin_amd64.tar.gz"
      sha256 "3f2869f75dc9344ceca5eb1cd2de2711aa99a6d16f3375dc7d2819d45e3632a6"

      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.5.1/ssm_0.5.1_darwin_arm64.tar.gz"
      sha256 "6256781827f56ab9f66b403e6cc55a4602b065c08c69861fd3a9bd3a0d0ae5b6"

      define_method(:install) do
        bin.install "ssm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.5.1/ssm_0.5.1_linux_amd64.tar.gz"
      sha256 "4201deea21cbf1d0d60053a3d5a61dade7df5ccde5e560f87bc9e4df73097731"
      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erhuoyan/ssm/releases/download/v0.5.1/ssm_0.5.1_linux_arm64.tar.gz"
      sha256 "56e902ca215e6aa137d0e44696380309d0e3b252cb3fa2e6a9aad3e1fa31548d"
      define_method(:install) do
        bin.install "ssm"
      end
    end
  end
end
